version: "3.9"
services:
  server:
    image: "nginx"
    ports:
      - 8080:80
      - 443:443
    volumes:
      - "${APP_PATH}:/var/www/"
      - "./nginx/hosts:/etc/nginx/conf.d"
  php:
    build: "./php"
    volumes:
    - "${APP_PATH}:/var/www"
  composer:
    image: composer
    volumes:
      - "${APP_PATH}:/app"
    working_dir: /app
    entrypoint: ["/bin/bash"]
